### ISSUE TITLE
Panning and zooming map with side menu open causes issues

### ISSUE THREAD

**Issue by mxdanger** [placeAtlas/atlas-2022#1376] opened 2022-05-31 00:16 UTC
When the canvas element has a margin-left applied to it the zoom origin is not correctly calculated while panning.

1. Open the side menu
2. Click and hold the slippy map
3. Without letting go, zoom in or out
4. After zooming, pan the map

After doing the last action the origin of the zoom will be shifted over by the amount of the margin-left. This also occurs when using a pinch and zoom on a touch screen device.

**Comment by Hans5958** [comment] 2023-07-21 16:57
It's been a while since the creation of this issue. Can you reproduce it again?

**Comment by Hans5958** [comment] 2023-07-24 11:08
I have fixed it in 2023 (https://2023.place-atlas.stefanocoding.me/), would you please test it if the issue still persist? (Do not close this issue if the issue is resolved. I will close it when I update the codebase)

**Closed** 2023-07-29 17:07 UTC
Labels: bug
