### ISSUE TITLE
Unable to click entry header link twice

### ISSUE THREAD

**Issue by mxdanger** [placeAtlas/atlas-2022#1372] opened 2022-05-19 03:59 UTC
If you click the header of an entry, where the link icon is, the entry is added to the url with the ID and timeline position, as expected.

However, if you click the same entry header again it does not update. A side effect of this is that if you have the entry already linked to in the url and you change the timeline position it's not possible to update it if you click the entry header.

**Comment by AnonymousRandomPerson** [comment] 2022-07-30 19:37
I'm not sure I understand the root issue here. Is the timeline position supposed to be added to the URL? I only see the ID added.

**Comment by mxdanger** [comment] 2022-08-01 06:35
Yes, the issue is that the timeline position should be added to the URL.

**Comment by ChengHannG** [comment] 2022-08-01 15:22
Oh, that's different from what the ticket implies.

"...the entry **is added** to the url with the ID and timeline position, **as expected**."
This uses the present tense, implying that the timeline is already added to the URL. And wouldn't this be an enhancement rather than a bug?

**Comment by AnonymousRandomPerson** [comment] 2022-08-01 15:23
Oh, that's different from what the ticket implies.

"...the entry **is added** to the url with the ID and timeline position, **as expected**."
This uses the present tense, implying that the timeline is already added to the URL. And wouldn't this be an enhancement rather than a bug?

**Comment by Hans5958** [comment] 2023-07-21 16:56
It's been a while since the change and I think the issue is gone (as in, you can click the entry header twice and more), so I can close it.

As of what to do when an entry does not exist in a certain period (discussed on #1384, iirc), this can be created as another issue, since it is worth discussing.

**Closed by Hans5958** 2023-07-21 16:56 UTC
Labels: bug
